### ISSUE TITLE
Starting Selma

### ISSUE THREAD

**Issue by daviddolan** [elixir-no-nels/Selma#17]
One thing I have found is that Selma can only be started from the place where it is installed and nothing in the user guide directly states this.

Is this intentional?

If so it seems a bit cumbersome for the end user that you can not start the tool from whatever folder you are working in given that most people would likely be in the folder where they intend the results to be written to rather than the Selma install directory.

**Comment by oskarvid** [comment]
It's intentional, it's possible to change but it would require a huge rewrite of the core of Selma. We can discuss this in our next meeting.

I have an idea about not making a fresh copy of Selma and instead only make a copy of the settings file because I think if Selma has a static installation directory the necessary paths can be set static as well. This is only an idea so far, whether it's desirable or even possible remains to be seen.

**Comment by oskarvid** [comment]
I remember now why I abandoned this idea the last time, the reason is that when you start a slurm job the slurm.out file needs to get written somewhere. Since Colossus only has read and write access to /cluster it's impossible to start it from anywhere else. So if the assumption is that the user should be able to start it from where they store their output files we simply can't fulfil this request.
We can discuss this idea further in the next meeting.
